$(document).ready(function () {


  var chooseCountry = document.getElementById("country-input");

  chooseCountry.innerHTML = '<option value="GHA" dir="auto">가나</option>'
  +'<option value="GAB" dir="auto">가봉</option>'
  +'ption value="GUY" dir="auto">가이아나</option>'
  +'<option value="GMB" dir="auto">감비아</option>'
  +'<option value="GGY" dir="auto">건지</option>'
  +'<option value="GLP" dir="auto">과들루프</option>'
  +'<option value="GTM" dir="auto">과테말라</option>'
  +'<option value="GUM" dir="auto">괌</option>'
  +'<option value="GRD" dir="auto">그레나다</option>'
  +'<option value="GRC" dir="auto">그리스</option>'
  +'<option value="GRL" dir="auto">그린란드</option>'
  +'<option value="GIN" dir="auto">기니</option>'
  +'<option value="GNB" dir="auto">기니비사우</option>'
  +'<option value="NAM" dir="auto">나미비아</option>'
  +'<option value="NRU" dir="auto">나우루</option>'
  +'<option value="NGA" dir="auto">나이지리아</option>'
  +'<option value="ATA" dir="auto">남극 대륙</option>'
  +'<option value="SSD" dir="auto">남수단</option>'
  +'<option value="ZAF" dir="auto">남아프리카 공화국</option>'
  +'<option value="NLD" dir="auto">네덜란드</option>'
  +'<option value="BES" dir="auto">네덜란드령 카리브</option>'
  +'<option value="NPL" dir="auto">네팔</option>'
  +'<option value="NOR" dir="auto">노르웨이</option>'
  +'<option value="NFK" dir="auto">노퍽섬</option>'
  +'<option value="NZL" dir="auto">뉴질랜드</option>'
  +'<option value="NCL" dir="auto">뉴칼레도니아</option>'
  +'<option value="NIU" dir="auto">니우에</option>'
  +'<option value="NER" dir="auto">니제르</option>'
  +'<option value="NIC" dir="auto">니카라과</option>'
  +'<option value="TWN" dir="auto">대만</option>'
  +'<option value="KOR" dir="auto" selected>대한민국</option>'
  +'<option value="DNK" dir="auto">덴마크</option>'
  +'<option value="DMA" dir="auto">도미니카</option>'
  +'<option value="DOM" dir="auto">도미니카 공화국</option>'
  +'<option value="DEU" dir="auto">독일</option>'
  +'<option value="TMP" dir="auto">동티모르</option>'
  +'<option value="LAO" dir="auto">라오스</option>'
  +'<option value="LBR" dir="auto">라이베리아</option>'
  +'<option value="LVA" dir="auto">라트비아</option>'
  +'<option value="RUS" dir="auto">러시아</option>'
  +'<option value="LBN" dir="auto">레바논</option>'
  +'<option value="LSO" dir="auto">레소토</option>'
  +'<option value="ROU" dir="auto">루마니아</option>'
  +'<option value="LUX" dir="auto">룩셈부르크</option>'
  +'<option value="RWA" dir="auto">르완다</option>'
  +'<option value="LBY" dir="auto">리비아</option>'
  +'<option value="REU" dir="auto">리유니온</option>'
  +'<option value="LTU" dir="auto">리투아니아</option>'
  +'<option value="LIE" dir="auto">리히텐슈타인</option>'
  +'<option value="MDG" dir="auto">마다가스카르</option>'
  +'<option value="MTQ" dir="auto">마르티니크</option>'
  +'<option value="MHL" dir="auto">마셜 제도</option>'
  +'<option value="MYT" dir="auto">마요트</option>'
  +'<option value="MAC" dir="auto">마카오</option>'
  +'<option value="MWI" dir="auto">말라위</option>'
  +'<option value="MYS" dir="auto">말레이시아</option>'
  +'<option value="MLI" dir="auto">말리</option>'
  +'<option value="IMN" dir="auto">맨 섬</option>'
  +'<option value="MEX" dir="auto">멕시코</option>'
  +'<option value="MCO" dir="auto">모나코</option>'
  +'<option value="MAR" dir="auto">모로코</option>'
  +'<option value="MUS" dir="auto">모리셔스</option>'
  +'<option value="MRT" dir="auto">모리타니</option>'
  +'<option value="MOZ" dir="auto">모잠비크</option>'
  +'<option value="MNE" dir="auto">몬테네그로</option>'
  +'<option value="MSR" dir="auto">몬트세라트</option>'
  +'<option value="MDA" dir="auto">몰도바</option>'
  +'<option value="MDV" dir="auto">몰디브</option>'
  +'<option value="MLT" dir="auto">몰타</option>'
  +'<option value="MNG" dir="auto">몽골</option>'
  +'<option value="USA" dir="auto">미국</option>'
  +'<option value="UMI" dir="auto">미국령 군소 제도</option>'
  +' <option value="VIR" dir="auto">미국령 버진아일랜드</option>'
  +'<option value="MMR" dir="auto">미얀마</option>'
  +'<option value="FSM" dir="auto">미크로네시아</option>'
  +'<option value="VUT" dir="auto">바누아투</option>'
  +'<option value="BHR" dir="auto">바레인</option>'
  +'<option value="BRB" dir="auto">바베이도스</option>'
  +'<option value="VAT" dir="auto">바티칸 시국</option>'
  +'<option value="BHS" dir="auto">바하마</option>'
  +'<option value="BGD" dir="auto">방글라데시</option>'
  +'<option value="BMU" dir="auto">버뮤다</option>'
  +'<option value="BEN" dir="auto">베냉</option>'
  +'<option value="VEN" dir="auto">베네수엘라</option>'
  +'<option value="VNM" dir="auto">베트남</option>'
  +'<option value="BEL" dir="auto">벨기에</option>'
  +'<option value="BLR" dir="auto">벨라루스</option>'
  +'<option value="BLZ" dir="auto">벨리즈</option>'
  +'<option value="BIH" dir="auto">보스니아 헤르체고비나</option>'
  +'<option value="BWA" dir="auto">보츠와나</option>'
  +'<option value="BOL" dir="auto">볼리비아</option>'
  +'<option value="BDI" dir="auto">부룬디</option>'
  +'<option value="BFA" dir="auto">부르키나파소</option>'
  +'<option value="BVT" dir="auto">부베섬</option>'
  +'<option value="BTN" dir="auto">부탄</option>'
  +'<option value="MNP" dir="auto">북마리아나제도</option>'
  +'<option value="MKD" dir="auto">북마케도니아</option>'
  +'<option value="BGR" dir="auto">불가리아</option>'
  +'<option value="BRA" dir="auto">브라질</option>'
  +'<option value="BRN" dir="auto">브루나이</option>'
  +'<option value="WSM" dir="auto">사모아</option>'
  +'<option value="SAU" dir="auto">사우디아라비아</option>'
  +'<option value="SGS" dir="auto">사우스조지아 사우스샌드위치 제도</option>'
  +'<option value="SMR" dir="auto">산마리노</option>'
  +'<option value="STP" dir="auto">상투메 프린시페</option>'
  +'<option value="MAF" dir="auto">생마르탱</option>'
  +'<option value="BLM" dir="auto">생바르텔르미</option>'
  +'<option value="SPM" dir="auto">생피에르 미클롱</option>'
  +'<option value="ESH" dir="auto">서사하라</option>'
  +'<option value="SEN" dir="auto">세네갈</option>'
  +'<option value="SRB" dir="auto">세르비아</option>'
  +'<option value="SYC" dir="auto">세이셸</option>'
  +'<option value="LCA" dir="auto">세인트루시아</option>'
  +'<option value="VCT" dir="auto">세인트빈센트그레나딘</option>'
  +'<option value="KNA" dir="auto">세인트키츠 네비스</option>'
  +'<option value="SHN" dir="auto">세인트 헬레나</option>'
  +'<option value="SOM" dir="auto">소말리아</option>'
  +'<option value="SLB" dir="auto">솔로몬 제도</option>'
  +'<option value="SDN" dir="auto">수단</option>'
  +'<option value="SUR" dir="auto">수리남</option>'
  +'<option value="LKA" dir="auto">스리랑카</option>'
  +'<option value="SJM" dir="auto">스발바르제도-얀마웬섬</option>'
  +'<option value="SWE" dir="auto">스웨덴</option>'
  +'<option value="CHE" dir="auto">스위스</option>'
  +'<option value="ESP" dir="auto">스페인</option>'
  +'<option value="SVK" dir="auto">슬로바키아</option>'
  +'<option value="SVN" dir="auto">슬로베니아</option>'
  +'<option value="SLE" dir="auto">시에라리온</option>'
  +'<option value="SXM" dir="auto">신트마르턴</option>'
  +'<option value="SGP" dir="auto">싱가포르</option>'
  +'<option value="ARE" dir="auto">아랍에미리트</option>'
  +'<option value="ABW" dir="auto">아루바</option>'
  +'<option value="ARM" dir="auto">아르메니아</option>'
  +'<option value="ARG" dir="auto">아르헨티나</option>'
  +'<option value="ASM" dir="auto">아메리칸 사모아</option>'
  +'<option value="ISL" dir="auto">아이슬란드</option>'
  +'<option value="HTI" dir="auto">아이티</option>'
  +'<option value="IRL" dir="auto">아일랜드</option>'
  +'<option value="AZE" dir="auto">아제르바이잔</option>'
  +'<option value="AFG" dir="auto">아프가니스탄</option>'
  +'<option value="AND" dir="auto">안도라</option>'
  +'<option value="ALB" dir="auto">알바니아</option>'
  +'<option value="DZA" dir="auto">알제리</option>'
  +' <option value="AGO" dir="auto">앙골라</option>'
  +'<option value="ATG" dir="auto">앤티가 바부다</option>'
  +'<option value="AIA" dir="auto">앵귈라</option>'
  +'<option value="ERI" dir="auto">에리트리아</option>'
  +'<option value="SWZ" dir="auto">에스와티니</option>'
  +'<option value="EST" dir="auto">에스토니아</option>'
  +'<option value="ECU" dir="auto">에콰도르</option>'
  +'<option value="ETH" dir="auto">에티오피아</option>'
  +'<option value="SLV" dir="auto">엘살바도르</option>'
  +'<option value="GBR" dir="auto">영국</option>'
  +'<option value="VGB" dir="auto">영국령 버진아일랜드</option>'
  +'<option value="IOT" dir="auto">영국령 인도양 식민지</option>'
  +'<option value="YEM" dir="auto">예멘</option>'
  +'<option value="OMN" dir="auto">오만</option>'
  +'<option value="AUS" dir="auto">오스트레일리아</option>'
  +'<option value="AUT" dir="auto">오스트리아</option>'
  +'<option value="HND" dir="auto">온두라스</option>'
  +'<option value="ALA" dir="auto">올란드 제도</option>'
  +'<option value="WLF" dir="auto">왈리스-푸투나 제도</option>'
  +'<option value="JOR" dir="auto">요르단</option>'
  +'<option value="UGA" dir="auto">우간다</option>'
  +'<option value="URY" dir="auto">우루과이</option>'
  +'<option value="UZB" dir="auto">우즈베키스탄</option>'
  +'<option value="UKR" dir="auto">우크라이나</option>'
  +'<option value="IRQ" dir="auto">이라크</option>'
  +'<option value="ISR" dir="auto">이스라엘</option>'
  +'<option value="EGY" dir="auto">이집트</option>'
  +'<option value="ITA" dir="auto">이탈리아</option>'
  +'<option value="IND" dir="auto">인도</option>'
  +'<option value="IDN" dir="auto">인도네시아</option>'
  +'<option value="JPN" dir="auto">일본</option>'
  +'<option value="JAM" dir="auto">자메이카</option>'
  +'<option value="ZMB" dir="auto">잠비아</option>'
  +'<option value="JEY" dir="auto">저지</option>'
  +'<option value="GNQ" dir="auto">적도기니</option>'
  +'<option value="GEO" dir="auto">조지아</option>'
  +' <option value="CHN" dir="auto">중국 본토</option>'
  +' <option value="CAF" dir="auto">중앙 아프리카 공화국</option>'
  +' <option value="DJI" dir="auto">지부티</option>'
  +' <option value="GIB" dir="auto">지브롤터</option>'
  +'  <option value="ZWE" dir="auto">짐바브웨</option>'
  +'  <option value="TCD" dir="auto">차드</option>'
  +' <option value="CZE" dir="auto">체코</option>'
  +' <option value="CHL" dir="auto">칠레</option>'
  +' <option value="CMR" dir="auto">카메룬</option>'
  +' <option value="CPV" dir="auto">카보베르데</option>'
  +' <option value="KAZ" dir="auto">카자흐스탄</option>'
  +' <option value="QAT" dir="auto">카타르</option>'
  +' <option value="KHM" dir="auto">캄보디아</option>'
  +'  <option value="CAN" dir="auto">캐나다</option>'
  +' <option value="KEN" dir="auto">케냐</option>'
  +' <option value="CYM" dir="auto">케이맨 제도</option>'
  +' <option value="COM" dir="auto">코모로</option>'
  +' <option value="XKS" dir="auto">코소보</option>'
  +' <option value="CRI" dir="auto">코스타리카</option>'
  +' <option value="CCK" dir="auto">코코스 제도</option>'
  +' <option value="CIV" dir="auto">코트디부아르</option>'
  +' <option value="COL" dir="auto">콜롬비아</option>'
  +' <option value="COG" dir="auto">콩고 공화국</option>'
  +' <option value="COD" dir="auto">콩고 민주 공화국</option>'
  +' <option value="KWT" dir="auto">쿠웨이트</option>'
  +'<option value="COK" dir="auto">쿡 제도</option>'
  +' <option value="CUW" dir="auto">퀴라소</option>'
  +'  <option value="HRV" dir="auto">크로아티아</option>'
  +' <option value="CXR" dir="auto">크리스마스섬</option>'
  +'  <option value="KGZ" dir="auto">키르기스스탄</option>'
  +' <option value="KIR" dir="auto">키리바시</option>'
  +'  <option value="CYP" dir="auto">키프로스</option>'
  +'  <option value="TJK" dir="auto">타지키스탄</option>'
  +'  <option value="TZA" dir="auto">탄자니아</option>'
  +' <option value="THA" dir="auto">태국</option>'
  +' <option value="TCA" dir="auto">터크스 케이커스 제도</option>'
  +' <option value="TUR" dir="auto">터키</option>'
  +' <option value="TGO" dir="auto">토고</option>'
  +' <option value="TKL" dir="auto">토켈라우</option>'
  +' <option value="TON" dir="auto">통가</option>'
  +' <option value="TKM" dir="auto">투르크메니스탄</option>'
  +' <option value="TUV" dir="auto">투발루</option>'
  +' <option value="TUN" dir="auto">튀니지</option>'
  +' <option value="TTO" dir="auto">트리니다드 토바고</option>'
  +' <option value="PAN" dir="auto">파나마</option>'
  +' <option value="PRY" dir="auto">파라과이</option>'
  +' <option value="PAK" dir="auto">파키스탄</option>'
  +' <option value="PNG" dir="auto">파푸아뉴기니</option>'
  +' <option value="PLW" dir="auto">팔라우</option>'
  +' <option value="PSE" dir="auto">팔레스타인</option>'
  +' <option value="FRO" dir="auto">페로 제도</option>'
  +' <option value="PER" dir="auto">페루</option>'
  +'<option value="PRT" dir="auto">포르투갈</option>'
  +'<option value="FLK" dir="auto">포클랜드 제도</option>'
  +'<option value="POL" dir="auto">폴란드</option>'
  +'<option value="PRI" dir="auto">푸에르토리코</option>'
  +'<option value="FRA" dir="auto">프랑스</option>'
  +'<option value="GUF" dir="auto">프랑스령 기아나</option>'
  +'<option value="ATF" dir="auto">프랑스령 남부 지방</option>'
  +'<option value="PYF" dir="auto">프랑스령 폴리네시아</option>'
  +'<option value="FJI" dir="auto">피지</option>'
  +'<option value="FIN" dir="auto">핀란드</option>'
  +'<option value="PHL" dir="auto">필리핀</option>'
  +'<option value="PCN" dir="auto">핏케언 섬</option>'
  +'<option value="HMD" dir="auto">허드 맥도널드 제도</option>'
  +'<option value="HUN" dir="auto">헝가리</option>'
  +'  <option value="HKG" dir="auto">홍콩</option>';



  var chooseCountry = document.getElementById("code-input");

  chooseCountry.innerHTML = '<option value="GH">+233 (가나)</option>'
  +'<option value="GA">+241 (가봉)</option>'
  +'<option value="GY">+592 (가이아나)</option>'
  +'  <option value="GM">+220 (감비아)</option>'
  +'  <option value="GG">+44 (건지)</option>'
  +'<option value="GP">+590 (과들루프)</option>'
  +'<option value="GT">+502 (과테말라)</option>'
  +'<option value="GU">+1 (괌)</option>'
  +'<option value="GD">+1 (그레나다)</option>'
  +'<option value="GR">+30 (그리스)</option>'
  +'<option value="GL">+299 (그린란드)</option>'
  +'<option value="GN">+224 (기니)</option>'
  +' <option value="GW">+245 (기니비사우)</option>'
  +' <option value="NA">+264 (나미비아)</option>'
  +' <option value="NR">+674 (나우루)</option>'
  +' <option value="NG">+234 (나이지리아)</option>'
  +' <option value="AQ">+672 (남극 대륙)</option>'
  +' <option value="SS">+211 (남수단)</option>'
  +'  <option value="ZA">+27 (남아프리카 공화국)</option>'
  +'  <option value="NL">+31 (네덜란드)</option>'
  +' <option value="BQ">+599 (네덜란드령 카리브)</option>'
  +' <option value="NP">+977 (네팔)</option>'
  +' <option value="NO">+47 (노르웨이)</option>'
  +' <option value="NZ">+64 (뉴질랜드)</option>'
  +' <option value="NC">+687 (뉴칼레도니아)</option>'
  +' <option value="NU">+683 (니우에)</option>'
  +' <option value="NE">+227 (니제르)</option>'
  +'<option value="NI">+505 (니카라과)</option>'
  +'<option value="TW">+886 (대만)</option>'
  +'<option value="KR" selected>+82 (대한민국)</option>'
  +'<option value="DK">+45 (덴마크)</option>'
  +'<option value="DM">+1 (도미니카)</option>'
  +'<option value="DO">+1 (도미니카 공화국)</option>'
  +'<option value="DE">+49 (독일)</option>'
  +' <option value="TP">+670 (동티모르)</option>'
  +'<option value="LA">+856 (라오스)</option>'
  +'<option value="LR">+231 (라이베리아)</option>'
  +'<option value="LV">+371 (라트비아)</option>'
  +'<option value="RU">+7 (러시아)</option>'
  +'<option value="LB">+961 (레바논</option>'
  +'<option value="LS">+266 (레소토)</option>'
  +'<option value="RO">+40 (루마니아)</option>'
  +'<option value="LU">+352 (룩셈부르크)</option>'
  +' <option value="RW">+250 (르완다)</option>'
  +'<option value="LY">+218 (리비아)</option>'
  +'<option value="RE">+262 (리유니온)</option>'
  +'<option value="LT">+370 (리투아니아)</option>'
  +'<option value="LI">+423 (리히텐슈타인)</option>'
  +'<option value="MG">+261 (마다가스카르)</option>'
  +'<option value="MQ">+596 (마르티니크)</option>'
  +'<option value="MH">+692 (마셜 제도)</option>'
  +'<option value="YT">+262 (마요트)</option>'
  +'<option value="MO">+853 (마카오)</option>'
  +'<option value="MW">+265 (말라위)</option>'
  +'<option value="MY">+60 (말레이시아)</option>'
  +'<option value="ML">+223 (말리)</option>'
  +'<option value="IM">+44 (맨 섬)</option>'
  +'<option value="MX">+52 (멕시코)</option>'
  +'<option value="MC">+377 (모나코)</option>'
  +'<option value="MA">+212 (모로코)</option>'
  +'<option value="MU">+230 (모리셔스)</option>'
  +'<option value="MR">+222 (모리타니)</option>'
  +'<option value="MZ">+258 (모잠비크)</option>'
  +'<option value="ME">+382 (몬테네그로)</option>'
  +'<option value="MS">+1 (몬트세라트)</option>'
  +'<option value="MD">+373 (몰도바)</option>'
  +'<option value="MV">+960 (몰디브)</option>'
  +'<option value="MT">+356 (몰타)</option>'
  +'<option value="MN">+976 (몽골)</option>'
  +'<option value="US">+1 (미국)</option>'
  +'<option value="VI">+1 (미국령 버진아일랜드)</option>'
  +'<option value="MM">+95 (미얀마)</option>'
  +'<option value="FM">+691 (미크로네시아)</option>'
  +'<option value="VU">+678 (바누아투)</option>'
  +'<option value="BH">+973 (바레인)</option>'
  +'<option value="BB">+1 (바베이도스)</option>'
  +' <option value="VA">+39 (바티칸 시국)</option>'
  +' <option value="BS">+1 (바하마)</option>'
  +' <option value="BD">+880 (방글라데시)</option>'
  +'<option value="BM">+1 (버뮤다)</option>'
  +' <option value="BJ">+229 (베냉)</option>'
  +'<option value="VE">+58 (베네수엘라)</option>'
  +'<option value="VN">+84 (베트남)</option>'
  +'<option value="BE">+32 (벨기에)</option>'
  +' <option value="BY">+375 (벨라루스)</option>'
  +'<option value="BZ">+501 (벨리즈)</option>'
  +'<option value="BA">+387 (보스니아 헤르체고비나)</option>'
  +'<option value="BW">+267 (보츠와나)</option>'
  +'<option value="BO">+591 (볼리비아)</option>'
  +'<option value="BI">+257 (부룬디)</option>'
  +'<option value="BF">+226 (부르키나파소)</option>'
  +'<option value="BV">+47 (부베섬)</option>'
  +'<option value="BT">+975 (부탄)</option>'
  +'<option value="MP">+1 (북마리아나제도)</option>'
  +'<option value="MK">+389 (북마케도니아)</option>'
  +'<option value="BG">+359 (불가리아)</option>'
  +'<option value="BR">+55 (브라질)</option>'
  +'<option value="BN">+673 (브루나이)</option>'
  +'<option value="WS">+685 (사모아)</option>'
  +'<option value="SA">+966 (사우디아라비아)</option>'
  +'<option value="SM">+378 (산마리노)</option>'
  +'<option value="ST">+239 (상투메 프린시페)</option>'
  +'<option value="MF">+1 (생마르탱)</option>'
  +'<option value="BL">+590 (생바르텔르미)</option>'
  +'<option value="PM">+508 (생피에르 미클롱)</option>'
  +'<option value="EH">+212 (서사하라)</option>'
  +'<option value="SN">+221 (세네갈)</option>'
  +'<option value="RS">+381 (세르비아)</option>'
  +'<option value="SC">+248 (세이셸)</option>'
  +'<option value="LC">+1 (세인트루시아)</option>'
  +'<option value="VC">+1 (세인트빈센트그레나딘)</option>'
  +'<option value="KN">+1 (세인트키츠 네비스)</option>'
  +'<option value="SH">+290 (세인트 헬레나)</option>'
  +'<option value="SO">+252 (소말리아)</option>'
  +'<option value="SB">+677 (솔로몬 제도)</option>'
  +'<option value="SD">+249 (수단)</option>'
  +'<option value="SR">+597 (수리남)</option>'
  +'<option value="LK">+94 (스리랑카)</option>'
  +'<option value="SJ">+47 (스발바르제도-얀마웬섬)</option>'
  +'<option value="SE">+46 (스웨덴)</option>'
  +'<option value="CH">+41 (스위스)</option>'
  +'<option value="ES">+34 (스페인)</option>'
  +'<option value="SK">+421 (슬로바키아)</option>'
  +'<option value="SI">+386 (슬로베니아)</option>'
  +'<option value="SL">+232 (시에라리온)</option>'
  +'<option value="SX">+1 (신트마르턴)</option>'
  +'<option value="SG">+65 (싱가포르)</option>'
  +'<option value="AE">+971 (아랍에미리트)</option>'
  +'<option value="AW">+297 (아루바)</option>'
  +'<option value="AM">+374 (아르메니아)</option>'
  +'<option value="AR">+54 (아르헨티나)</option>'
  +'<option value="AS">+1 (아메리칸 사모아)</option>'
  +'<option value="IS">+354 (아이슬란드)</option>'
  +'<option value="HT">+509 (아이티)</option>'
  +'<option value="IE">+353 (아일랜드)</option>'
  +'<option value="AZ">+994 (아제르바이잔)</option>'
  +'<option value="AF">+93 (아프가니스탄)</option>'
  +'<option value="AD">+376 (안도라)</option>'
  +'<option value="AL">+355 (알바니아)</option>'
  +'<option value="DZ">+213 (알제리)</option>'
  +'<option value="AO">+244 (앙골라)</option>'
  +'<option value="AG">+1 (앤티가 바부다)</option>'
  +'<option value="AI">+1 (앵귈라)</option>'
  +'<option value="ER">+291 (에리트리아)</option>'
  +'<option value="SZ">+268 (에스와티니)</option>'
  +'<option value="EE">+372 (에스토니아)</option>'
  +'<option value="EC">+593 (에콰도르)</option>'
  +'<option value="ET">+251 (에티오피아)</option>'
  +'<option value="SV">+503 (엘살바도르)</option>'
  +'<option value="GB">+44 (영국)</option>'
  +'<option value="VG">+1 (영국령 버진아일랜드)</option>'
  +'<option value="IO">+246 (영국령 인도양 식민지)</option>'
  +'<option value="YE">+967 (예멘)</option>'
  +'<option value="OM">+968 (오만)</option>'
  +'<option value="AU">+61 (오스트레일리아)</option>'
  +'<option value="AT">+43 (오스트리아)</option>'
  +'<option value="HN">+504 (온두라스)</option>'
  +'<option value="AX">+358 (올란드 제도)</option>'
  +'<option value="WF">+681 (왈리스-푸투나 제도)</option>'
  +'<option value="JO">+962 (요르단)</option>'
  +'<option value="UG">+256 (우간다)</option>'
  +'<option value="UY">+598 (우루과이)</option>'
  +'<option value="UZ">+998 (우즈베키스탄)</option>'
  +'<option value="UA">+380 (우크라이나)</option>'
  +'<option value="IQ">+964 (이라크)</option>'
  +'<option value="IL">+972 (이스라엘)</option>'
  +'<option value="EG">+20 (이집트)</option>'
  +'<option value="IT">+39 (이탈리아)</option>'
  +'<option value="IN">+91 (인도)</option>'
  +'<option value="ID">+62 (인도네시아)</option>'
  +'<option value="JP">+81 (일본)</option>'
  +'<option value="JM">+1 (자메이카)</option>'
  +'<option value="ZM">+260 (잠비아)</option>'
  +'<option value="JE">+44 (저지)</option>'
  +'<option value="GQ">+240 (적도기니)</option>'
  +'<option value="GE">+995 (조지아)</option>'
  +'<option value="CN">+86 (중국 본토)</option>'
  +'<option value="CF">+236 (중앙 아프리카 공화국)</option>'
  +'<option value="DJ">+253 (지부티)</option>'
  +'<option value="GI">+350 (지브롤터)</option>'
  +'<option value="ZW">+263 (짐바브웨)</option>'
  +'<option value="TD">+235 (차드)</option>'
  +'<option value="CZ">+420 (체코)</option>'
  +'<option value="CL">+56 (칠레)</option>'
  +'<option value="CM">+237 (카메룬)</option>'
  +'<option value="CV">+238 (카보베르데)</option>'
  +'<option value="KZ">+7 (카자흐스탄)</option>'
  +'<option value="QA">+974 (카타르)</option>'
  +'<option value="KH">+855 (캄보디아)</option>'
  +'<option value="CA">+1 (캐나다)</option>'
  +'<option value="KE">+254 (케냐)</option>'
  +'<option value="KY">+1 (케이맨 제도)</option>'
  +'<option value="KM">+269 (코모로)</option>'
  +'<option value="XK">+383 (코소보)</option>'
  +'<option value="CR">+506 (코스타리카)</option>'
  +'<option value="CC">+61 (코코스 제도)</option>'
  +'<option value="CI">+225 (코트디부아르)</option>'
  +'<option value="CO">+57 (콜롬비아)</option>'
  +'<option value="CG">+242 (콩고 공화국)</option>'
  +'<option value="CD">+243 (콩고 민주 공화국)</option>'
  +'<option value="KW">+965 (쿠웨이트)</option>'
  +'<option value="CK">+682 (쿡 제도)</option>'
  +'<option value="CW">+599 (퀴라소)</option>'
  +'<option value="HR">+385 (크로아티아)</option>'
  +'<option value="CX">+61 (크리스마스섬)</option>'
  +'<option value="KG">+996 (키르기스스탄)</option>'
  +'<option value="KI">+686 (키리바시)</option>'
  +'<option value="CY">+357 (키프로스)</option>'
  +'<option value="TJ">+992 (타지키스탄)</option>'
  +'<option value="TZ">+255 (탄자니아)</option>'
  +'<option value="TH">+66 (태국)</option>'
  +'<option value="TC">+1 (터크스 케이커스 제도)</option>'
  +'<option value="TR">+90 (터키)</option>'
  +'<option value="TG">+228 (토고)</option>'
  +'<option value="TK">+690 (토켈라우)</option>'
  +'<option value="TO">+676 (통가)</option>'
  +'<option value="TM">+993 (투르크메니스탄)</option>'
  +'<option value="TV">+688 (투발루)</option>'
  +'<option value="TN">+216 (튀니지)</option>'
  +'<option value="TT">+1 (트리니다드 토바고)</option>'
  +'<option value="PA">+507 (파나마)</option>'
  +'<option value="PY">+595 (파라과이)</option>'
  +'<option value="PK">+92 (파키스탄)</option>'
  +'<option value="PG">+675 (파푸아뉴기니)</option>'
  +'<option value="PW">+680 (팔라우)</option>'
  +'<option value="PS">+970 (팔레스타인)</option>'
  +'<option value="FO">+298 (페로 제도)</option>'
  +'<option value="PE">+51 (페루)</option>'
  +'<option value="PT">+351 (포르투갈)</option>'
  +'<option value="FK">+500 (포클랜드 제도)</option>'
  +'<option value="PL">+48 (폴란드)</option>'
  +'<option value="PR">+1 (푸에르토리코)</option>'
  +'<option value="FR">+33 (프랑스)</option>'
  +'<option value="GF">+594 (프랑스령 기아나)</option>'
  +'<option value="TF">+262 (프랑스령 남부 지방)</option>'
  +'<option value="PF">+689 (프랑스령 폴리네시아)</option>'
  +'<option value="FJ">+679 (피지)</option>'
  +'<option value="FI">+358 (핀란드)</option>'
  +'<option value="PH">+63 (필리핀)</option>'
  +'<option value="PN">+870 (핏케언 섬)</option>'
  +'<option value="HM">+61 (허드 맥도널드 제도)</option>'
  +'<option value="HU">+36 (헝가리)</option>'
  +' <option value="HK">+852 (홍콩)</option>'
  

});